'use client';

import { useEffect, useRef } from 'react';
import { useUIStore } from '@/store/useUIStore';
import { useDossierStore } from '@/store/useDossierStore';
import { useFacturationStore } from '@/store/useFacturationStore';
import { usePlanningStore } from '@/store/usePlanningStore';
import { useStockStore } from '@/store/useStockStore';
import { useIntervenantStore } from '@/store/useIntervenantStore';
import { useHistoryStore } from '@/store/useHistoryStore';
import { useConfigStore } from '@/store/useConfigStore';
import type { AlertItem, AlertSeverity, AlertCategory, AlertAction } from '@/store/useUIStore';

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Parse "dd/mm/yyyy" → Date (ou null si invalide) */
function parseFR(str?: string): Date | null {
  if (!str) return null;
  // Supporte dd/mm/yyyy et yyyy-mm-dd
  const parts = str.includes('/') ? str.split('/') : null;
  if (parts && parts.length === 3) {
    const d = new Date(+parts[2], +parts[1] - 1, +parts[0]);
    return isNaN(d.getTime()) ? null : d;
  }
  const d = new Date(str);
  return isNaN(d.getTime()) ? null : d;
}

/** Nombre de jours entre deux dates (positif = passé) */
function daysSince(date: Date, from: Date = new Date()): number {
  return Math.floor((from.getTime() - date.getTime()) / 86_400_000);
}

/** Date d'aujourd'hui à minuit */
function today(): Date {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  return d;
}

/** Demain à minuit */
function tomorrow(): Date {
  const d = today();
  d.setDate(d.getDate() + 1);
  return d;
}

/** Après-demain */
function dayAfterTomorrow(): Date {
  const d = today();
  d.setDate(d.getDate() + 2);
  return d;
}

type RawAlert = Omit<AlertItem, 'id' | 'createdAt' | 'dismissed'>;

// ── Le moteur ────────────────────────────────────────────────────────────────

function computeAlerts(): RawAlert[] {
  const alerts: RawAlert[] = [];
  const now = today();

  // ── Récupérer tous les états ──
  const { dossiers, dossiersSignes, datesButoiresSignes } = useDossierStore.getState();
  const { invoices, invoiceDetails, devis, payments } = useFacturationStore.getState();
  const { planningEvents, gestEvents } = usePlanningStore.getState();
  const { stockItems, commandes } = useStockStore.getState();
  const { intervenants } = useIntervenantStore.getState();
  const { relances } = useHistoryStore.getState();
  const { relanceConfig, notifConfig } = useConfigStore.getState();

  // ═══════════════════════════════════════════════════════════════════════════
  // 1. DOSSIERS
  // ═══════════════════════════════════════════════════════════════════════════

  // #1 — Date butoir dépassée ou proche (dossiers signés) — utilise datesButoiresSignes
  for (const ds of dossiersSignes) {
    const savedDates = datesButoiresSignes[ds.id] ?? {};
    // Aussi vérifier l'ancien système dateButoires pour la rétrocompatibilité
    const legacyDates: Record<string, string> = {};
    if (ds.dateButoires) {
      const labels: Record<string, string> = {
        suiviChantier: 'Suivi chantier',
        releveMesures: 'Relevé de mesures',
        planTechnique: 'Plan technique',
        fichePose: 'Fiche de pose',
        permisConstruire: 'Permis de construire',
        sav: 'SAV',
      };
      for (const [key, label] of Object.entries(labels)) {
        const v = (ds.dateButoires as Record<string, string | undefined>)[key];
        if (v) legacyDates[label] = v;
      }
    }

    // Nouveau système
    for (const [label, dateStr] of Object.entries(savedDates)) {
      const date = parseFR(dateStr);
      if (!date) continue;
      const daysUntil = -daysSince(date, now); // positif = dans le futur
      const daysLate = daysSince(date, now);
      if (daysLate > 0) {
        alerts.push({
          severity: 'error',
          category: 'dossier',
          text: `${ds.name} — "${label}" en retard de ${daysLate}j`,
          dossierId: ds.id,
          sourceKey: `butoir-${ds.id}-${label}`,
          autoGenerated: true,
          actions: [
            { label: 'Voir dossier', href: `/dossiers/${ds.id}` },
            { label: 'Relancer client', action: 'relance_client' },
          ],
        });
      } else if (daysUntil <= 7) {
        alerts.push({
          severity: 'warning',
          category: 'dossier',
          text: `${ds.name} — "${label}" dans ${daysUntil}j`,
          dossierId: ds.id,
          sourceKey: `butoir-soon-${ds.id}-${label}`,
          autoGenerated: true,
          actions: [{ label: 'Voir dossier', href: `/dossiers/${ds.id}` }],
        });
      }
    }

    // Système legacy
    for (const [label, dateStr] of Object.entries(legacyDates)) {
      const date = parseFR(dateStr);
      if (date && date < now) {
        const days = daysSince(date, now);
        alerts.push({
          severity: 'error',
          category: 'dossier',
          text: `${ds.name} — "${label}" en retard de ${days}j`,
          dossierId: ds.id,
          sourceKey: `butoir-legacy-${ds.id}-${label}`,
          autoGenerated: true,
          actions: [
            { label: 'Voir dossier', href: `/dossiers/${ds.id}` },
            { label: 'Relancer client', action: 'relance_client' },
          ],
        });
      }
    }
  }

  // #2 — Acompte non reçu
  for (const ds of dossiersSignes) {
    const signedDate = parseFR(ds.signedDate);
    if (!signedDate) continue;
    const delai = relanceConfig.delaiAcompte || 7;
    if (daysSince(signedDate, now) < delai) continue;
    // Vérifier s'il existe un paiement acompte pour ce dossier
    const hasAcompte = payments.some(
      p => p.dossierId === ds.id && p.type?.toLowerCase().includes('acompte') && p.statut === 'ENCAISSÉ'
    );
    if (!hasAcompte) {
      alerts.push({
        severity: 'warning',
        category: 'facturation',
        text: `${ds.name} — Acompte non reçu (signé il y a ${daysSince(signedDate, now)}j)`,
        dossierId: ds.id,
        sourceKey: `acompte-${ds.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Envoyer relance', action: 'relance_acompte' },
          { label: 'Voir dossier', href: `/dossiers/${ds.id}` },
        ],
      });
    }
  }

  // #3 — Confirmation fournisseur en attente
  for (const ds of dossiersSignes) {
    if (!ds.confirmations) continue;
    for (const conf of ds.confirmations) {
      if (conf.validee) continue;
      const dateButoir = parseFR(conf.dateButoir);
      if (dateButoir && daysSince(dateButoir, now) > 7) {
        alerts.push({
          severity: 'warning',
          category: 'commande',
          text: `${ds.name} — Confirmation "${conf.fournisseur}" en attente depuis ${daysSince(dateButoir, now)}j`,
          dossierId: ds.id,
          sourceKey: `conf-${ds.id}-${conf.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Appeler fournisseur', action: 'appeler_fournisseur' },
            { label: 'Voir dossier', href: `/dossiers/${ds.id}` },
          ],
        });
      }
    }
  }

  // #4 — Dossier inactif > 30 jours
  for (const d of dossiers) {
    const created = parseFR(d.createdAt);
    if (created && daysSince(created, now) > 30) {
      alerts.push({
        severity: 'info',
        category: 'dossier',
        text: `${d.name} — Inactif depuis ${daysSince(created, now)}j`,
        dossierId: d.id,
        sourceKey: `inactif-${d.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Relancer', action: 'relance_client' },
          { label: 'Archiver', action: 'archiver_dossier' },
        ],
      });
    }
  }

  // #5 — Nouveau dossier créé (dans les 24 dernières heures)
  if (notifConfig.nouveauDossier) {
    for (const d of dossiers) {
      const created = parseFR(d.createdAt);
      if (created && daysSince(created, now) === 0) {
        alerts.push({
          severity: 'info',
          category: 'dossier',
          text: `Nouveau dossier créé : ${d.name}`,
          dossierId: d.id,
          sourceKey: `nouveau-${d.id}`,
          autoGenerated: true,
          actions: [{ label: 'Voir dossier', href: `/dossiers/${d.id}` }],
        });
      }
    }
  }

  // #6 — Dossier marqué URGENT
  for (const d of dossiers) {
    if (d.status === 'URGENT') {
      alerts.push({
        severity: 'error',
        category: 'dossier',
        text: `${d.name} — Dossier URGENT`,
        dossierId: d.id,
        sourceKey: `urgent-${d.id}`,
        autoGenerated: true,
        actions: [{ label: 'Voir dossier', href: `/dossiers/${d.id}` }],
      });
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. FACTURATION
  // ═══════════════════════════════════════════════════════════════════════════

  // #7 — Facture en retard (dateEcheance dépassée)
  if (notifConfig.factureRetard) {
    for (const inv of invoices) {
      if (inv.statut === 'PAYÉE' || inv.statut === 'AVOIR') continue;
      const detail = invoiceDetails[inv.id];
      const echeance = parseFR(detail?.dateEcheance);
      if (echeance && echeance < now) {
        alerts.push({
          severity: 'error',
          category: 'facturation',
          text: `Facture ${inv.ref} (${inv.client}) — Échéance dépassée de ${daysSince(echeance, now)}j`,
          dossierId: inv.dossierId,
          sourceKey: `facture-echeance-${inv.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Envoyer relance', action: 'relance_facture' },
            { label: 'Voir facture', href: '/facturation' },
          ],
        });
      }
    }
  }

  // #8 — Facture avec statut RETARD
  if (notifConfig.factureRetard) {
    for (const inv of invoices) {
      if (inv.statut !== 'RETARD') continue;
      const dateInv = parseFR(inv.date);
      const retardJours = dateInv ? daysSince(dateInv, now) : 0;
      alerts.push({
        severity: 'error',
        category: 'facturation',
        text: `Facture ${inv.ref} (${inv.client}) — EN RETARD${retardJours > 0 ? ` (${retardJours}j)` : ''}`,
        dossierId: inv.dossierId,
        sourceKey: `facture-retard-${inv.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Relance retard', action: 'relance_retard' },
          { label: 'Appeler client', action: 'appeler_client' },
          { label: 'Voir facture', href: '/facturation' },
        ],
      });
    }
  }

  // #9 — Facture d'acompte en attente trop longtemps
  for (const inv of invoices) {
    if (inv.type !== "Facture d'acompte" || inv.statut !== 'EN ATTENTE') continue;
    const dateInv = parseFR(inv.date);
    const delai = relanceConfig.delaiAcompte || 7;
    if (dateInv && daysSince(dateInv, now) > delai) {
      alerts.push({
        severity: 'warning',
        category: 'facturation',
        text: `Acompte ${inv.ref} (${inv.client}) — En attente depuis ${daysSince(dateInv, now)}j`,
        dossierId: inv.dossierId,
        sourceKey: `acompte-facture-${inv.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Relancer', action: 'relance_acompte' },
          { label: 'Voir facture', href: '/facturation' },
        ],
      });
    }
  }

  // #10 — Paiement reçu (dans les 24h)
  if (notifConfig.paiementRecu) {
    for (const p of payments) {
      if (p.statut !== 'ENCAISSÉ') continue;
      const datePay = parseFR(p.date);
      if (datePay && daysSince(datePay, now) === 0) {
        alerts.push({
          severity: 'info',
          category: 'facturation',
          text: `Paiement reçu de ${p.client} — ${p.amount.toLocaleString('fr-FR')}€ (${p.method})`,
          dossierId: p.dossierId,
          sourceKey: `paiement-${p.id}`,
          autoGenerated: true,
          actions: [{ label: 'Voir facture', href: '/facturation' }],
        });
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. DEVIS
  // ═══════════════════════════════════════════════════════════════════════════

  // #11 — Devis expiré
  if (notifConfig.devisExpire) {
    for (const d of devis) {
      if (d.statut === 'ACCEPTÉ' || d.statut === 'REFUSÉ' || d.statut === 'EXPIRÉ') continue;
      const validite = parseFR(d.dateValidite);
      if (validite && validite < now) {
        alerts.push({
          severity: 'warning',
          category: 'devis',
          text: `Devis ${d.ref} (${d.client}) — Expiré depuis ${daysSince(validite, now)}j`,
          dossierId: d.dossierId,
          sourceKey: `devis-expire-${d.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Relancer client', action: 'relance_devis' },
            { label: 'Prolonger', action: 'prolonger_devis' },
            { label: 'Archiver', action: 'archiver_devis' },
          ],
        });
      }
    }
  }

  // #12 — Devis en attente de signature > 5 jours
  for (const d of devis) {
    if (d.signatureStatus !== 'EN_ATTENTE_SIGNATURE') continue;
    const dateCreation = parseFR(d.dateCreation);
    if (dateCreation && daysSince(dateCreation, now) > 5) {
      alerts.push({
        severity: 'warning',
        category: 'devis',
        text: `Devis ${d.ref} (${d.client}) — En attente de signature depuis ${daysSince(dateCreation, now)}j`,
        dossierId: d.dossierId,
        sourceKey: `devis-signature-${d.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Rappeler client', action: 'relance_signature' },
          { label: 'Renvoyer lien', action: 'renvoyer_lien' },
        ],
      });
    }
  }

  // #13 — Devis refusé
  for (const d of devis) {
    if (d.statut !== 'REFUSÉ') continue;
    alerts.push({
      severity: 'info',
      category: 'devis',
      text: `Devis ${d.ref} (${d.client}) — Refusé`,
      dossierId: d.dossierId,
      sourceKey: `devis-refuse-${d.id}`,
      autoGenerated: true,
      actions: [
        { label: 'Analyser', href: '/facturation' },
        { label: 'Archiver en perdu', action: 'archiver_perdu' },
      ],
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. PLANNING
  // ═══════════════════════════════════════════════════════════════════════════

  if (notifConfig.planningRappel) {
    const todayDay = now.getDay(); // 0=dim, 1=lun, ...
    const tomorrowDay = (todayDay + 1) % 7;

    // #14 — Intervention demain (planningEvents)
    for (const ev of planningEvents) {
      const evOffset = ev.weekOffset ?? 0;
      if (evOffset === 0 && ev.day === tomorrowDay) {
        alerts.push({
          severity: 'clock',
          category: 'planning',
          text: `Demain ${ev.startHour}h — ${ev.title}`,
          sourceKey: `planning-demain-${ev.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Voir planning', href: '/planning' },
          ],
        });
      }
    }

    // #15 — Intervention demain (gestEvents — livraisons, visites)
    for (const ev of gestEvents) {
      if (ev.weekOffset === 0 && ev.day === tomorrowDay) {
        const typeLabel = ev.type === 'LIVRAISON' ? 'Livraison' :
                          ev.type === 'VISITE_CHANTIER' ? 'Visite chantier' :
                          ev.type === 'INSTALLATION' ? 'Installation' : ev.type;
        alerts.push({
          severity: 'clock',
          category: 'planning',
          text: `Demain ${ev.startHour}h — ${typeLabel} chez ${ev.client}`,
          sourceKey: `gestion-demain-${ev.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Voir planning', href: '/planning-gestion' },
            { label: 'Appeler poseur', action: 'appeler_poseur' },
          ],
        });
      }
    }

    // #16 — Visite chantier passée non faite (semaine précédente)
    for (const ev of gestEvents) {
      if (ev.type !== 'VISITE_CHANTIER') continue;
      if (ev.weekOffset === -1 || (ev.weekOffset === 0 && ev.day < todayDay)) {
        alerts.push({
          severity: 'warning',
          category: 'planning',
          text: `Visite chantier non effectuée — ${ev.client}`,
          sourceKey: `visite-manquee-${ev.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Replanifier', href: '/planning-gestion' },
          ],
        });
      }
    }

    // #17 — Conflit planning (2 events au même créneau)
    const slots = new Map<string, string[]>();
    for (const ev of planningEvents) {
      if ((ev.weekOffset ?? 0) !== 0) continue;
      for (let h = ev.startHour; h < ev.startHour + ev.duration; h++) {
        const key = `${ev.day}-${h}`;
        const existing = slots.get(key) || [];
        existing.push(ev.title);
        slots.set(key, existing);
      }
    }
    for (const [slot, titles] of slots.entries()) {
      if (titles.length >= 2) {
        const [day, hour] = slot.split('-');
        alerts.push({
          severity: 'warning',
          category: 'planning',
          text: `Conflit planning — ${titles.join(' / ')} (${['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'][+day]} ${hour}h)`,
          sourceKey: `conflit-${slot}`,
          autoGenerated: true,
          actions: [{ label: 'Voir planning', href: '/planning' }],
        });
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. STOCK & COMMANDES
  // ═══════════════════════════════════════════════════════════════════════════

  // #18 — Stock critique (orange)
  for (const item of stockItems) {
    if (item.quantity != null && item.minQuantity != null && item.quantity > 0 && item.quantity <= item.minQuantity) {
      alerts.push({
        severity: 'warning',
        category: 'stock',
        text: `Stock critique — ${item.supplier} ${item.model} (${item.quantity}/${item.minQuantity})`,
        sourceKey: `stock-critique-${item.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Commander', action: 'commander_stock' },
          { label: 'Voir stock', href: '/stock' },
        ],
      });
    }
  }

  // #19 — Rupture de stock (rouge)
  for (const item of stockItems) {
    if (item.dot === 'red' || (item.quantity != null && item.quantity === 0)) {
      alerts.push({
        severity: 'error',
        category: 'stock',
        text: `Rupture de stock — ${item.supplier} ${item.model}`,
        sourceKey: `stock-rupture-${item.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Commander en urgence', action: 'commander_urgence' },
          { label: 'Voir stock', href: '/stock' },
        ],
      });
    }
  }

  // #20 — Commande en attente > 3 jours
  if (notifConfig.commandeAttente) {
    for (const cmd of commandes) {
      if (cmd.statut !== 'EN ATTENTE') continue;
      const dateCmd = parseFR(cmd.dateCommande);
      if (dateCmd && daysSince(dateCmd, now) > 3) {
        alerts.push({
          severity: 'warning',
          category: 'commande',
          text: `Commande ${cmd.reference} (${cmd.fournisseur}) — En attente depuis ${daysSince(dateCmd, now)}j`,
          dossierId: cmd.dossierId,
          sourceKey: `cmd-attente-${cmd.id}`,
          autoGenerated: true,
          actions: [
            { label: 'Confirmer', action: 'confirmer_commande' },
            { label: 'Relancer fournisseur', action: 'relance_fournisseur' },
          ],
        });
      }
    }
  }

  // #21 — Livraison en retard
  for (const cmd of commandes) {
    if (cmd.statut === 'LIVRÉE' || cmd.statut === 'ANNULÉE') continue;
    const dateLiv = parseFR(cmd.dateLivraison);
    if (dateLiv && dateLiv < now) {
      alerts.push({
        severity: 'error',
        category: 'commande',
        text: `Livraison en retard — ${cmd.fournisseur} (${cmd.reference}), prévu il y a ${daysSince(dateLiv, now)}j`,
        dossierId: cmd.dossierId,
        sourceKey: `cmd-livraison-${cmd.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Appeler fournisseur', action: 'appeler_fournisseur' },
        ],
      });
    }
  }

  // #22 — Commande annulée
  for (const cmd of commandes) {
    if (cmd.statut !== 'ANNULÉE') continue;
    const dateCmd = parseFR(cmd.dateCommande);
    if (dateCmd && daysSince(dateCmd, now) < 7) {
      alerts.push({
        severity: 'info',
        category: 'commande',
        text: `Commande annulée — ${cmd.fournisseur} (${cmd.reference})`,
        dossierId: cmd.dossierId,
        sourceKey: `cmd-annulee-${cmd.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Nouvelle commande', action: 'nouvelle_commande' },
        ],
      });
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. INTERVENANTS
  // ═══════════════════════════════════════════════════════════════════════════

  // #23 — Intervenant avec dossier(s) "A CLASSER" depuis longtemps
  for (const interv of intervenants) {
    const aClasser = interv.dossiers.filter(d => d.statut === 'A CLASSER');
    if (aClasser.length > 0) {
      alerts.push({
        severity: 'warning',
        category: 'intervenant',
        text: `${interv.name} — ${aClasser.length} dossier(s) à classer`,
        sourceKey: `interv-aclasser-${interv.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Voir intervenants', href: '/intervenants' },
        ],
      });
    }
  }

  // #24 — Intervenant sans email/phone (données incomplètes)
  for (const interv of intervenants) {
    if (!interv.email && !interv.phone) {
      alerts.push({
        severity: 'info',
        category: 'intervenant',
        text: `${interv.name} — Coordonnées incomplètes (pas d'email ni de tél.)`,
        sourceKey: `interv-incomplet-${interv.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Compléter', href: '/intervenants' },
        ],
      });
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 7. RELANCES AUTOMATIQUES
  // ═══════════════════════════════════════════════════════════════════════════

  // #24b — Relances automatiques hebdomadaires pour dates butoires
  // Si une date butoire est définie et dans moins de 21j, rappel hebdo automatique
  for (const ds of dossiersSignes) {
    const savedDates = datesButoiresSignes[ds.id] ?? {};
    for (const [label, dateStr] of Object.entries(savedDates)) {
      const date = parseFR(dateStr);
      if (!date) continue;
      const daysUntil = -daysSince(date, now);
      // Rappel si dans 14j, 7j ou 3j (niveaux de relance)
      if (daysUntil === 14) {
        alerts.push({
          severity: 'info',
          category: 'relance',
          text: `${ds.name} — Rappel J-14 : "${label}" dans 2 semaines`,
          dossierId: ds.id,
          sourceKey: `relance-auto-j14-${ds.id}-${label}`,
          autoGenerated: true,
          actions: [{ label: 'Voir dossier', href: `/dossiers/${ds.id}` }],
        });
      } else if (daysUntil === 7) {
        alerts.push({
          severity: 'warning',
          category: 'relance',
          text: `${ds.name} — Rappel J-7 : "${label}" dans 1 semaine`,
          dossierId: ds.id,
          sourceKey: `relance-auto-j7-${ds.id}-${label}`,
          autoGenerated: true,
          actions: [
            { label: 'Relancer client', action: 'relance_client' },
            { label: 'Voir dossier', href: `/dossiers/${ds.id}` },
          ],
        });
      } else if (daysUntil === 3) {
        alerts.push({
          severity: 'error',
          category: 'relance',
          text: `${ds.name} — URGENT J-3 : "${label}" dans 3 jours !`,
          dossierId: ds.id,
          sourceKey: `relance-auto-j3-${ds.id}-${label}`,
          autoGenerated: true,
          actions: [
            { label: 'Relancer client', action: 'relance_client' },
            { label: 'Appeler client', action: 'appeler_client' },
            { label: 'Voir dossier', href: `/dossiers/${ds.id}` },
          ],
        });
      }
    }
  }

  // #25, #26, #27 — Relances actives à envoyer
  for (const rel of relances) {
    if (rel.status !== 'active') continue;
    const nextDate = parseFR(rel.dateNextRelance);
    if (nextDate && nextDate <= now) {
      const sevMap: Record<string, AlertSeverity> = {
        acompte: 'warning',
        confirmation: 'warning',
        dossier_vente: 'warning',
        date_butoire: 'error',
      };
      const labelMap: Record<string, string> = {
        acompte: 'Relance acompte',
        confirmation: 'Relance confirmation',
        dossier_vente: 'Relance solde',
        date_butoire: 'Relance date butoir',
      };
      alerts.push({
        severity: sevMap[rel.type] ?? 'warning',
        category: 'relance',
        text: `${labelMap[rel.type] ?? 'Relance'} — ${rel.message}`,
        dossierId: rel.dossierId,
        sourceKey: `relance-${rel.id}`,
        autoGenerated: true,
        actions: [
          { label: 'Envoyer relance', action: 'envoyer_relance' },
          { label: 'Reporter', action: 'reporter_relance' },
        ],
      });
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 8. ADMINISTRATION
  // ═══════════════════════════════════════════════════════════════════════════

  // #28 — Pas de données société configurées
  const { societe } = useConfigStore.getState();
  if (!societe.nom && !societe.siret) {
    alerts.push({
      severity: 'info',
      category: 'admin',
      text: 'Coordonnées société non renseignées — Paramètres incomplets',
      sourceKey: 'admin-societe-vide',
      autoGenerated: true,
      actions: [{ label: 'Configurer', href: '/parametres' }],
    });
  }

  // ── Trier par sévérité ──
  const order: Record<AlertSeverity, number> = { error: 0, warning: 1, clock: 2, info: 3 };
  alerts.sort((a, b) => order[a.severity] - order[b.severity]);

  return alerts;
}

// ── Hook React ───────────────────────────────────────────────────────────────

/**
 * Hook qui fait tourner le moteur d'alertes toutes les 30 secondes.
 * À monter dans le layout principal.
 */
export function useAlertEngine() {
  const setGeneratedAlerts = useUIStore(s => s.setGeneratedAlerts);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    // Premier calcul immédiat
    const run = () => {
      try {
        const alerts = computeAlerts();
        setGeneratedAlerts(alerts);
      } catch (e) {
        console.error('[AlertEngine] Erreur:', e);
      }
    };

    // Léger délai pour laisser les stores s'hydrater
    const timeout = setTimeout(run, 1000);

    // Recalcul toutes les 30 secondes
    intervalRef.current = setInterval(run, 30_000);

    return () => {
      clearTimeout(timeout);
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [setGeneratedAlerts]);
}
