/**
 * Store UI — états d'interface (modales, alertes, sidebar, etc.)
 */
import { create } from 'zustand';

// Types
export type AlertSeverity = 'error' | 'warning' | 'info' | 'clock';

export type AlertCategory =
  | 'dossier'
  | 'facturation'
  | 'devis'
  | 'planning'
  | 'stock'
  | 'commande'
  | 'intervenant'
  | 'relance'
  | 'admin';

export interface AlertAction {
  label: string;
  href?: string;        // navigation link
  action?: string;      // action key (pour l'assistant)
}

export interface AlertItem {
  id: string;
  severity: AlertSeverity;
  category: AlertCategory;
  text: string;
  dossierId?: string;
  dismissed: boolean;
  createdAt: string;
  sourceKey?: string;   // clé unique pour dédupliquer (ex: "facture-retard-inv123")
  actions?: AlertAction[];
  autoGenerated?: boolean;
}

// Helper
const uid = () => crypto.randomUUID().replace(/-/g, '').slice(0, 8);

const now = () => {
  const d = new Date();
  return `${d.toLocaleDateString('fr-FR')} ${d.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })}`;
};

interface UIState {
  // Data
  alerts: AlertItem[];

  // UI State
  sidebarOpen: boolean;
  modalOpen: string | null;

  // Alert actions
  addAlert: (alert: Omit<AlertItem, 'id' | 'createdAt' | 'dismissed'>) => void;
  dismissAlert: (id: string) => void;
  setGeneratedAlerts: (alerts: Omit<AlertItem, 'id' | 'createdAt' | 'dismissed'>[]) => void;

  // UI actions
  toggleSidebar: () => void;
  setSidebarOpen: (open: boolean) => void;
  openModal: (name: string) => void;
  closeModal: () => void;

  // Reset
  reset: () => void;
}

export const useUIStore = create<UIState>((set, get) => ({
  alerts: [],
  sidebarOpen: true,
  modalOpen: null,

  addAlert: (alert) => {
    const existing = get().alerts;
    // Dédupliquer par sourceKey
    if (alert.sourceKey && existing.some(a => a.sourceKey === alert.sourceKey && !a.dismissed)) return;
    const newAlert: AlertItem = {
      ...alert,
      id: 'a' + uid(),
      dismissed: false,
      createdAt: now(),
    };
    set(s => ({ alerts: [newAlert, ...s.alerts].slice(0, 100) }));
  },

  dismissAlert: (id) => {
    set(s => ({ alerts: s.alerts.map(a => a.id === id ? { ...a, dismissed: true } : a) }));
  },

  /**
   * Remplace toutes les alertes auto-générées par un nouveau lot.
   * Conserve les alertes manuelles et les alertes dismissed.
   */
  setGeneratedAlerts: (newAlerts) => {
    const existing = get().alerts;
    // Garder les alertes manuelles (non auto-générées)
    const manual = existing.filter(a => !a.autoGenerated);
    // Garder les sourceKeys dismissed pour ne pas les recréer
    const dismissedKeys = new Set(
      existing.filter(a => a.dismissed && a.sourceKey).map(a => a.sourceKey)
    );
    // Créer les nouvelles alertes en filtrant les dismissed
    const generated: AlertItem[] = newAlerts
      .filter(a => !dismissedKeys.has(a.sourceKey))
      .map(a => ({
        ...a,
        id: 'a' + uid(),
        dismissed: false,
        createdAt: now(),
        autoGenerated: true,
      }));
    set({ alerts: [...generated, ...manual].slice(0, 100) });
  },

  toggleSidebar: () => {
    set(s => ({ sidebarOpen: !s.sidebarOpen }));
  },

  setSidebarOpen: (open) => {
    set({ sidebarOpen: open });
  },

  openModal: (name) => {
    set({ modalOpen: name });
  },

  closeModal: () => {
    set({ modalOpen: null });
  },

  reset: () => set({
    alerts: [],
    sidebarOpen: true,
    modalOpen: null,
  }),
}));
